### ISSUE TITLE
notice

### ISSUE THREAD

**Issue by MorganBergen** [MorganBergen/clarity#61]
###  expect the following output

and message me for the api keys, you will need their values stored in an `.env` 

```console
❯ npm run dev

> clarity-backend@1.0.0 dev
> nodemon server.js

[nodemon] 3.1.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node server.js`
file:///Users/owner/Documents/03-GitHub/clarity-backup/clarity/server/node_modules/openai/index.mjs:42
            throw new Errors.OpenAIError("The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).");
                  ^

OpenAIError: The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).
    at new OpenAI (file:///Users/owner/Documents/03-GitHub/clarity-backup/clarity/server/node_modules/openai/index.mjs:42:19)
    at file:///Users/owner/Documents/03-GitHub/clarity-backup/clarity/server/routes/api.js:14:16
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12)

Node.js v18.20.4
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by MorganBergen** [comment]
I added information regarding the need for the `.env` in readme.md in branch/commit [`62-python-microservice` `f3369ee`]
